In [5]:
#KNN 
#importing required libraries
import numpy as np
import pandas as pd
from sklearn import neighbors, metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [30]:
#reading the data
data = pd.read_csv('car.data')
data

vhigh vhigh.1      2   2.1  small   low  unacc
0     vhigh   vhigh      2     2  small   med  unacc
1     vhigh   vhigh      2     2  small  high  unacc
2     vhigh   vhigh      2     2    med   low  unacc
3     vhigh   vhigh      2     2    med   med  unacc
4     vhigh   vhigh      2     2    med  high  unacc
...     ...     ...    ...   ...    ...   ...    ...
1722    low     low  5more  more    med   med   good
1723    low     low  5more  more    med  high  vgood
1724    low     low  5more  more    big   low  unacc
1725    low     low  5more  more    big   med   good
1726    low     low  5more  more    big  high  vgood

[1727 rows x 7 columns]

In [8]:
# As our data didnt had column titles we can Add heading to columns this way:
data.columns=['buying','maintainence','doors','persons','lug_boots','safety','class']

In [9]:
data.head()

buying maintainence doors persons lug_boots safety  class
0  vhigh        vhigh     2       2     small    med  unacc
1  vhigh        vhigh     2       2     small   high  unacc
2  vhigh        vhigh     2       2       med    low  unacc
3  vhigh        vhigh     2       2       med    med  unacc
4  vhigh        vhigh     2       2       med   high  unacc

In [19]:
# The features are the descriptive attributes, and the label is what we're attempting to predict or forecast.
# Here we are assigning features and attributes to x and y which means by looking at these impt features(buy,main,safe)
# we can predict class

X = data[[
    'buying',
    'maintainence',
    'safety'
]].values

y = data[['class']]

print(X,y)

[['vhigh' 'vhigh' 'med']
 ['vhigh' 'vhigh' 'high']
 ['vhigh' 'vhigh' 'low']
 ...
 ['low' 'low' 'low']
 ['low' 'low' 'med']
 ['low' 'low' 'high']]       class
0     unacc
1     unacc
2     unacc
3     unacc
4     unacc
...     ...
1722   good
1723  vgood
1724  unacc
1725   good
1726  vgood

[1727 rows x 1 columns]


In [62]:
# We have a strings that are categorical and can be converted into numbers. SO we use encoder.

Le = LabelEncoder()
for i in range(len(X[0])):
    X[: , i] = Le.fit_transform(X[:,i])
print(X)

[[3 3 2]
 [3 3 0]
 [3 3 1]
 ...
 [1 1 1]
 [1 1 2]
 [1 1 0]]


In [25]:
label_mapping = {
    'unacc': 0,
    'acc':1,
    'good':2,
    'vgood':2
}
y['class']=y['class'].map(label_mapping)
y=np.array(y)

<ipython-input-25-43ebc8882651>:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y['class']=y['class'].map(label_mapping)


In [26]:
print(y)

[[0]
 [0]
 [0]
 ...
 [0]
 [2]
 [2]]


In [31]:
knn = neighbors.KNeighborsClassifier(n_neighbors=25, weights = 'uniform')

In [32]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size = 0.2)
knn.fit(X_train,y_train)

/Users/yashadmuthe/opt/anaconda3/lib/python3.8/site-packages/sklearn/neighbors/_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=25)

In [41]:
Prediction = knn.predict(X_test)
accuracy = metrics.accuracy_score(y_test,Prediction)
print("prediction:",Prediction)
print("accuracy:",accuracy)

prediction: [0 2 1 0 1 2 1 0 1 0 0 0 0 0 2 1 0 0 2 2 0 0 0 1 0 0 2 0 0 0 2 1 0 1 1 2 0
 2 0 2 0 0 0 0 0 0 0 1 2 0 0 0 0 1 0 0 0 1 1 1 0 0 2 0 2 0 0 0 0 0 0 0 0 0
 0 2 0 1 0 1 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 2 2 0 0 0 0 0 1 2 2 0 1 0 0 0
 0 0 0 0 0 2 0 0 0 1 0 0 0 0 1 0 2 0 2 0 2 0 2 1 0 0 0 2 0 1 0 0 0 0 0 0 0
 2 0 1 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 0 0 0 1 2 2 2 0 2 2 1 0 2 2 1 0 0 1 0
 2 0 2 0 0 0 0 0 2 0 2 0 1 0 0 0 1 0 2 1 0 2 0 0 2 0 1 0 1 0 2 0 2 1 0 0 0
 1 0 0 0 0 1 0 0 1 0 0 0 0 0 2 0 2 1 0 1 0 1 0 0 0 2 1 0 1 0 0 0 0 1 0 0 0
 0 1 0 0 0 1 0 0 2 0 1 0 0 0 0 1 1 0 2 0 1 0 0 0 0 0 0 2 0 1 0 0 0 0 2 0 0
 1 0 1 0 0 1 0 0 1 0 1 0 0 0 0 0 0 0 2 0 0 2 0 1 0 0 2 0 1 2 0 0 0 0 0 0 0
 1 0 2 0 0 0 0 0 1 1 0 0 0]
accuracy: 0.7543352601156069


In [42]:
print("actual_value: ", y[20])
print("predicted_value: ", knn.predict(X)[20])

actual_value:  [0]
predicted_value:  0


In [59]:
a= 1726
print("actual_value: ", y[a])
print("predicted_value: ", knn.predict(X)[a])

actual_value:  [2]
predicted_value:  2


In [60]:
X[0]

array([3, 3, 2], dtype=object)